// Glosar de finanțare pentru startupuri — eligibil.org
// 180+ termeni grupați pe litere, cu tag-uri pentru filtrare.
// slug folosit pentru deep-link: /glosar#trl, /glosar#mvp, etc.
// tags: startup-basics, granturi, investitii, acceleratoare, ue, sbir,
//       trl-deeptech, consortii, aplicare, scoring, buget, produs,
//       metrici, growth, fundraising, ecosistem

const ORG_GLOSAR = [
  // A
  { slug: 'a-b-testing', term: 'A/B testing', body: 'Metodă prin care compari două versiuni ale unei pagini, reclame, email, pitch, formular sau funcționalități pentru a vedea care performează mai bine.\n\nÎn startupuri, A/B testing ajută echipa să ia decizii pe baza datelor, nu a presupunerilor. Poți testa titluri, prețuri, call-to-action-uri, pagini de aplicare sau mesaje către investitori.', example: 'Testezi două variante de landing page pentru un grant și vezi care generează mai multe înscrieri.', tags: ['produs', 'growth', 'metrici'] },
  { slug: 'accelerator', term: 'Accelerator', body: 'Program care ajută startupurile să crească rapid prin mentorat, training, networking, acces la investitori, cloud credits, suport tehnic sau finanțare.\n\nUnele acceleratoare sunt non-dilutive, adică nu cer equity. Altele oferă bani în schimbul unui procent din companie. Pentru fondatori, un accelerator este util nu doar pentru capital, ci și pentru validare, contacte, vizibilitate și pregătire pentru fundraising.', example: 'Google for Startups Accelerator, Techcelerator, Upcelerator.', tags: ['acceleratoare', 'fundraising', 'ecosistem'] },
  { slug: 'acquisition', term: 'Acquisition', body: 'Procesul prin care un startup atrage utilizatori sau clienți noi.\n\nCanalele de acquisition pot fi organice sau plătite: SEO, ads, outbound sales, parteneriate, comunități, evenimente, PR, marketplace-uri sau referral.\n\nÎn finanțare, evaluatorii vor să vadă dacă startupul are un canal realist de atragere a clienților.', tags: ['growth', 'metrici', 'produs'] },
  { slug: 'activation', term: 'Activation', body: 'Momentul în care un utilizator nou înțelege valoarea produsului și face prima acțiune importantă.', example: 'În eligibil.org, activation poate fi momentul în care utilizatorul încarcă pitch deck-ul și primește primul scor de eligibilitate.', tags: ['produs', 'metrici'] },
  { slug: 'advisor', term: 'Advisor', body: 'Persoană cu experiență care ajută startupul cu strategie, produs, fundraising, vânzări, tehnologie, legislație, finanțare sau acces la rețea.\n\nUn advisor bun poate crește credibilitatea startupului într-o aplicație de grant sau în fața investitorilor, mai ales dacă are experiență în domeniul vizat.', tags: ['ecosistem', 'fundraising'] },
  { slug: 'advisory-board', term: 'Advisory board', body: 'Grup de advisori care oferă ghidare periodică startupului.\n\nPoate fi informal sau formal. În aplicații de grant, advisory board-ul poate demonstra că echipa are acces la expertiză externă relevantă.', tags: ['ecosistem', 'aplicare'] },
  { slug: 'ai-readiness', term: 'AI Readiness', body: 'Gradul în care un startup este pregătit să fie analizat automat de un sistem AI pe baza documentelor, datelor și descrierilor disponibile.\n\nUn startup cu AI Readiness ridicat are pitch deck clar, date financiare, descriere de produs, website, whitepaper, TRL estimat, tracțiune și nevoi de finanțare bine definite.', tags: ['scoring', 'aplicare'] },
  { slug: 'angel-investor', term: 'Angel investor', body: 'Investitor individual care finanțează startupuri aflate la început, de obicei în schimbul unui procent din companie.\n\nAngel investors apar frecvent în runde pre-seed sau seed și pot oferi, pe lângă bani, mentorat, contacte și credibilitate.', example: 'Apar la runde pre-seed sau seed.', tags: ['investitii', 'fundraising'] },
  { slug: 'apel-finantare', term: 'Apel de finanțare', body: 'Oportunitate oficială prin care o instituție, fond, accelerator sau program invită aplicanții să depună proiecte.\n\nUn apel de finanțare include de obicei deadline, criterii de eligibilitate, buget disponibil, domenii acceptate, documente necesare, proces de evaluare și calendarul selecției.', tags: ['granturi', 'aplicare'] },
  { slug: 'aplicant', term: 'Aplicant', body: 'Persoana, startupul, compania, universitatea, institutul sau organizația care depune o aplicație pentru finanțare.\n\nÎn granturile colaborative, pot exista mai mulți aplicanți în același consorțiu, dar de obicei unul dintre ei are rol de coordonator.', tags: ['granturi', 'consortii', 'aplicare'] },
  { slug: 'aplicatie', term: 'Aplicație', body: 'Dosarul complet trimis către un program de finanțare.\n\nPoate include formular online, pitch deck, business plan, buget, whitepaper, CV-uri, scrisori de susținere, plan de impact, documente juridice, proiecții financiare și dovezi de tracțiune.', tags: ['aplicare', 'granturi'] },
  { slug: 'arr', term: 'ARR / Annual Recurring Revenue', body: 'Venit anual recurent, folosit mai ales la startupurile SaaS sau la modelele cu abonament.\n\nFormula simplă: ARR = MRR × 12.\n\nARR este un indicator important pentru investitori deoarece arată predictibilitatea veniturilor.', tags: ['metrici', 'investitii'] },
  { slug: 'artifact', term: 'Artifact', body: 'Document sau fișier încărcat pentru analiză.\n\nÎn eligibil.org, artefactele sunt folosite pentru a calcula Match Score, Readiness Score, Confidence Score și recomandări de finanțare.', example: 'Pitch deck, video pitch, whitepaper, business plan, website, one-pager, model financiar, raport de impact.', tags: ['scoring', 'aplicare'] },

  // B
  { slug: 'b2b', term: 'B2B', body: 'Business to Business. Model în care startupul vinde produse sau servicii altor companii.', example: 'Software pentru companii, platforme de HR, instrumente de cybersecurity, soluții de automatizare industrială.', tags: ['startup-basics', 'produs'] },
  { slug: 'b2c', term: 'B2C', body: 'Business to Consumer. Model în care startupul vinde direct consumatorilor individuali.', example: 'Aplicații mobile, marketplace-uri pentru consumatori, produse educaționale, health apps.', tags: ['startup-basics', 'produs'] },
  { slug: 'b2g', term: 'B2G', body: 'Business to Government. Model în care startupul vinde către instituții publice, autorități sau organizații guvernamentale.\n\nAcest model poate avea cicluri de vânzare mai lungi, dar contracte mai mari și impact public mai clar.', tags: ['startup-basics', 'produs'] },
  { slug: 'backlog', term: 'Backlog', body: 'Listă de funcționalități, buguri, idei, îmbunătățiri și sarcini pe care echipa intenționează să le dezvolte.\n\nÎn aplicații de grant, backlog-ul poate fi transformat într-un roadmap tehnic sau într-o listă de work packages.', tags: ['produs', 'aplicare'] },
  { slug: 'benchmark', term: 'Benchmark', body: 'Punct de referință folosit pentru comparație.\n\nUn startup poate compara rata de conversie, CAC, churn, ARR, TRL, performanța tehnică sau costurile cu media industriei.', tags: ['metrici'] },
  { slug: 'beta', term: 'Beta', body: 'Versiune de produs testată cu un grup limitat de utilizatori înainte de lansarea publică.\n\nO versiune beta poate demonstra progres tehnic, validare de piață și interes real din partea utilizatorilor.', tags: ['produs', 'startup-basics'] },
  { slug: 'blended-finance', term: 'Blended finance', body: 'Finanțare combinată din mai multe surse, de exemplu grant plus equity, grant plus împrumut sau finanțare publică plus capital privat.\n\nEste folosită frecvent pentru proiecte cu risc tehnologic ridicat sau pentru startupuri deep tech care au nevoie de capital semnificativ.', example: 'EIC Accelerator poate combina grant cu investiție equity opțională.', tags: ['fundraising', 'granturi', 'investitii'] },
  { slug: 'bootstrapping', term: 'Bootstrapping', body: 'Creșterea startupului folosind resurse proprii, venituri din clienți sau economiile fondatorilor, fără investiții externe majore.\n\nBootstrapping păstrează controlul fondatorilor, dar poate limita viteza de creștere.', tags: ['fundraising', 'startup-basics'] },
  { slug: 'bootstrapped-startup', term: 'Bootstrapped startup', body: 'Startup construit fără capital extern semnificativ.\n\nAcest tip de startup se bazează pe venituri, disciplină financiară și creștere organică.', tags: ['startup-basics', 'fundraising'] },
  { slug: 'burn-rate', term: 'Burn rate', body: 'Cât cheltuie startupul lunar pentru a funcționa.\n\nBurn rate-ul este important pentru calcularea runway-ului.', example: 'Dacă startupul cheltuie €15.000 pe lună, burn rate-ul este €15.000/lună.', tags: ['metrici', 'buget'] },
  { slug: 'buget-eligibil', term: 'Buget eligibil', body: 'Costuri acceptate de programul de finanțare.\n\nNu toate cheltuielile unui startup sunt eligibile. Unele programe acceptă salarii, echipamente, cercetare, subcontractare, consultanță, deplasări sau prototipare. Altele exclud marketingul, TVA-ul, achizițiile din afara perioadei proiectului sau cheltuielile fără documente justificative.', tags: ['buget', 'granturi', 'aplicare'] },
  { slug: 'business-model', term: 'Business model', body: 'Modul prin care startupul creează, livrează și captează valoare.', example: 'Abonament SaaS, comision, marketplace fee, licență, usage-based pricing, servicii, freemium, hardware plus software.', tags: ['startup-basics', 'produs'] },
  { slug: 'business-plan', term: 'Business plan', body: 'Document care explică produsul, piața, modelul de business, strategia de creștere, echipa, bugetul și proiecțiile financiare.\n\nÎn finanțare, business plan-ul trebuie să arate că proiectul este fezabil, sustenabil și are potențial de impact.', tags: ['aplicare', 'startup-basics'] },

  // C
  { slug: 'cac', term: 'CAC / Customer Acquisition Cost', body: 'Costul mediu pentru a obține un client nou.\n\nFormula simplă: CAC = costuri de marketing și vânzări / număr de clienți noi.\n\nCAC este esențial pentru a înțelege dacă startupul poate crește profitabil.', tags: ['metrici', 'growth'] },
  { slug: 'call', term: 'Call', body: 'Termen folosit pentru un apel de finanțare.\n\nÎn programele europene, un "call" este o competiție deschisă pentru depunerea proiectelor. Fiecare call are temă, buget, criterii, deadline și documentație oficială.', tags: ['ue', 'granturi', 'aplicare'] },
  { slug: 'cap-table', term: 'Cap table', body: 'Tabel care arată cine deține ce procent din companie: fondatori, investitori, angajați, advisori sau opțiuni pentru echipă.\n\nUn cap table curat este important în due diligence și fundraising.', tags: ['investitii', 'fundraising'] },
  { slug: 'capital-dilutiv', term: 'Capital dilutiv', body: 'Finanțare primită în schimbul unui procent din companie.\n\nFondatorii cedează equity către investitori, acceleratoare sau fonduri. Capitalul dilutiv poate accelera creșterea, dar reduce procentul deținut de fondatori.', example: 'Investiție VC, angel investment, unele acceleratoare.', tags: ['investitii', 'fundraising'] },
  { slug: 'capital-non-dilutiv', term: 'Capital non-dilutiv', body: 'Finanțare care nu cere cedarea unui procent din companie.\n\nEste atractivă pentru fondatori deoarece permite dezvoltarea startupului fără diluarea acționariatului.', example: 'Granturi, premii, vouchere, cloud credits, contracte de cercetare, unele acceleratoare fără equity.', tags: ['granturi', 'fundraising'] },
  { slug: 'cash-flow', term: 'Cash flow', body: 'Mișcarea banilor care intră și ies din companie.\n\nUn startup poate avea venituri, dar cash flow slab dacă încasează târziu sau cheltuie mai repede decât primește bani.', tags: ['metrici', 'buget'] },
  { slug: 'cash-runway', term: 'Cash runway', body: 'Perioada în care startupul poate funcționa cu banii disponibili înainte să rămână fără capital.', example: 'Dacă startupul are €120.000 și cheltuie €20.000 pe lună, runway-ul este de 6 luni.', tags: ['metrici', 'buget'] },
  { slug: 'churn', term: 'Churn', body: 'Rata la care clienții sau utilizatorii renunță la produs.\n\nChurn-ul este important mai ales pentru SaaS și abonamente. Un churn mare indică probleme de valoare, onboarding, preț, suport sau potrivire cu piața.', tags: ['metrici', 'produs'] },
  { slug: 'cloud-credits', term: 'Cloud credits', body: 'Credite oferite de furnizori cloud pentru utilizarea serviciilor de infrastructură.\n\nCloud credits sunt o formă de suport non-dilutiv.', example: 'AWS credits, Google Cloud credits, Microsoft Azure credits.', tags: ['acceleratoare', 'fundraising'] },
  { slug: 'cofinantare', term: 'Cofinanțare', body: 'Contribuția financiară pe care aplicantul trebuie să o aducă pentru a primi grantul.\n\nCofinanțarea poate fi cash, contribuție proprie sau uneori contribuție în natură, în funcție de program.', example: 'Programul finanțează 70%, iar startupul trebuie să acopere 30%.', tags: ['buget', 'granturi'] },
  { slug: 'cohort', term: 'Cohort', body: 'Grup de utilizatori sau startupuri analizat împreună pe o perioadă.\n\nÎn acceleratoare, o cohortă este grupa de startupuri acceptate într-un program. În produs, cohortele ajută la analiza retenției.', tags: ['acceleratoare', 'metrici'] },
  { slug: 'competition', term: 'Competition / competiție startup', body: 'Program competitiv unde startupurile aplică, sunt evaluate și pot primi premii, granturi, vizibilitate, mentorat sau acces la investitori.', tags: ['acceleratoare', 'ecosistem'] },
  { slug: 'competitive-advantage', term: 'Competitive advantage', body: 'Avantajul care face startupul greu de copiat.', example: 'Tehnologie proprie, date exclusive, distribuție unică, IP, brand, rețea, costuri mai mici, parteneriate strategice.', tags: ['startup-basics', 'produs'] },
  { slug: 'confidence-score', term: 'Confidence Score', body: 'Scor care arată cât de sigure sunt concluziile unei analize pe baza calității și cantității datelor disponibile.\n\nÎn eligibil.org, Confidence Score poate crește dacă startupul încarcă pitch deck, video, whitepaper, website, model financiar și date de tracțiune.', tags: ['scoring'] },
  { slug: 'consortiu', term: 'Consorțiu', body: 'Grup de organizații care aplică împreună la un grant sau proiect.\n\nÎn programele europene, consorțiile includ adesea startupuri, IMM-uri, universități, institute de cercetare, companii mari, autorități publice și organizații sectoriale.', example: 'Un proiect Horizon Europe poate cere minimum 3 parteneri din 3 țări diferite.', tags: ['consortii', 'ue', 'granturi'] },
  { slug: 'conversion-rate', term: 'Conversion rate', body: 'Procentul utilizatorilor care fac o acțiune dorită.', example: 'Din 1.000 de vizitatori, 50 creează cont. Conversion rate = 5%.', tags: ['metrici', 'growth'] },
  { slug: 'coordinator', term: 'Coordinator / coordonator', body: 'Organizația principală dintr-un consorțiu.\n\nCoordonatorul este responsabil de depunerea proiectului, comunicarea cu finanțatorul, coordonarea partenerilor, raportare și management administrativ.', tags: ['consortii', 'granturi'] },
  { slug: 'cost-structure', term: 'Cost structure', body: 'Structura costurilor startupului.\n\nInclude costuri fixe, costuri variabile, salarii, infrastructură, marketing, vânzări, R&D, operațiuni și subcontractare.', tags: ['buget', 'startup-basics'] },
  { slug: 'costuri-directe', term: 'Costuri directe', body: 'Cheltuieli legate direct de proiect.', example: 'Salarii pentru echipa de proiect, echipamente, materiale, subcontractare, servicii tehnice, testare, prototipare.', tags: ['buget', 'granturi'] },
  { slug: 'costuri-indirecte', term: 'Costuri indirecte', body: 'Cheltuieli generale care susțin proiectul, dar nu pot fi atribuite direct unei activități.', example: 'Chirie, utilități, administrație, contabilitate, management general.', tags: ['buget', 'granturi'] },
  { slug: 'customer-development', term: 'Customer development', body: 'Proces continuu prin care validezi problema, soluția, piața și modelul de business cu clienți reali.\n\nEste o metodă esențială pentru a evita construirea unui produs pe care piața nu îl dorește.', tags: ['startup-basics', 'produs'] },
  { slug: 'customer-discovery', term: 'Customer discovery', body: 'Procesul de discuții cu potențiali clienți pentru a înțelege problema, nevoia, comportamentul, bugetul și disponibilitatea de plată.', tags: ['startup-basics', 'produs'] },

  // D
  { slug: 'data-room', term: 'Data room', body: 'Spațiu organizat cu documentele importante ale startupului, folosit pentru investitori, granturi, acceleratoare sau due diligence.', example: 'Pitch deck, acte juridice, cap table, finanțe, contracte, IP, roadmap, documente tehnice, rapoarte, politici interne.', tags: ['fundraising', 'aplicare'] },
  { slug: 'deadline', term: 'Deadline', body: 'Data limită până la care trebuie depusă aplicația.\n\nÎn granturi, depășirea deadline-ului înseamnă de obicei respingere automată.', tags: ['granturi', 'aplicare'] },
  { slug: 'deep-tech', term: 'Deep tech', body: 'Startup bazat pe cercetare, tehnologie avansată sau inovație științifică greu de replicat.\n\nDeep tech are adesea cicluri de dezvoltare mai lungi, risc tehnologic mai ridicat și nevoie de granturi R&D.', example: 'AI avansat, biotech, robotics, quantum, materiale noi, hardware, space, climate tech, semiconductori.', tags: ['trl-deeptech', 'granturi'] },
  { slug: 'deliverable', term: 'Deliverable', body: 'Rezultat concret pe care un proiect trebuie să îl livreze către finanțator.', example: 'Raport tehnic, prototip, studiu de piață, software demonstrabil, plan de exploatare, raport de impact.', tags: ['granturi', 'aplicare'] },
  { slug: 'demo-day', term: 'Demo Day', body: 'Eveniment la finalul unui accelerator unde startupurile prezintă în fața investitorilor, partenerilor și comunității.', tags: ['acceleratoare', 'fundraising'] },
  { slug: 'design-partner', term: 'Design partner', body: 'Client sau partener timpuriu care testează produsul și oferă feedback detaliat.\n\nDesign partners pot ajuta startupul să valideze problema, soluția și roadmap-ul.', tags: ['produs', 'startup-basics'] },
  { slug: 'dilution', term: 'Dilution / diluare', body: 'Reducerea procentului deținut de fondatori sau investitori existenți după emiterea de noi acțiuni.\n\nDiluarea apare de obicei când startupul ridică o rundă de investiție.', tags: ['investitii', 'fundraising'] },
  { slug: 'discovery-call', term: 'Discovery call', body: 'Discuție inițială cu un potențial client, partener, investitor, accelerator sau finanțator pentru a înțelege nevoile și potrivirea.', tags: ['fundraising', 'startup-basics'] },
  { slug: 'dissemination', term: 'Dissemination', body: 'Activități prin care rezultatele unui proiect sunt comunicate către public, industrie, comunitate științifică sau stakeholderi.\n\nÎn granturile europene, dissemination este deseori un work package separat.', tags: ['ue', 'granturi'] },
  { slug: 'distribution', term: 'Distribution', body: 'Modul prin care produsul ajunge la clienți.', example: 'Sales direct, SEO, marketplace, parteneriate, comunități, app stores, resellers, integratori.', tags: ['growth', 'produs'] },
  { slug: 'due-diligence', term: 'Due diligence', body: 'Procesul prin care un finanțator verifică startupul înainte de investiție sau finanțare.\n\nPoate include verificarea echipei, documentelor juridice, finanțelor, IP-ului, pieței, tehnologiei, riscurilor, contractelor și cap table-ului.', tags: ['investitii', 'fundraising'] },

  // E
  { slug: 'early-adopter', term: 'Early adopter', body: 'Client sau utilizator care încearcă produsul devreme, înainte să fie complet matur.\n\nEarly adopters sunt importanți pentru feedback, validare și primele dovezi de tracțiune.', tags: ['startup-basics', 'produs'] },
  { slug: 'early-stage-startup', term: 'Early-stage startup', body: 'Startup aflat la început, de obicei cu MVP, prime validări, echipă mică și tracțiune inițială.', tags: ['startup-basics'] },
  { slug: 'eic-accelerator', term: 'EIC Accelerator', body: 'Program al European Innovation Council pentru startupuri și IMM-uri cu tehnologii inovatoare, în special deep tech.\n\nPoate oferi grant și investiție equity. Este potrivit pentru startupuri cu tehnologie avansată, potențial de piață european sau global și risc tehnologic ridicat.', example: 'Potrivit pentru startupuri cu TRL avansat, de obicei TRL 6–8.', tags: ['ue', 'granturi', 'trl-deeptech'] },
  { slug: 'eic-pathfinder', term: 'EIC Pathfinder', body: 'Program european pentru cercetare avansată și tehnologii emergente.\n\nDe obicei implică proiecte colaborative și consorții. Este orientat spre idei high-risk / high-gain și tehnologii aflate în faze timpurii.', tags: ['ue', 'consortii', 'trl-deeptech'] },
  { slug: 'eic-transition', term: 'EIC Transition', body: 'Program care ajută proiectele de cercetare să treacă spre validare, prototipare și comercializare.\n\nEste potrivit pentru echipe care au rezultate de cercetare promițătoare și vor să le transforme în aplicații reale.', tags: ['ue', 'trl-deeptech', 'granturi'] },
  { slug: 'eligibility', term: 'Eligibility / eligibilitate', body: 'Condițiile pe care trebuie să le îndeplinească un startup pentru a putea aplica la un program.\n\nPoate include țara, forma juridică, domeniul, stadiul, TRL-ul, veniturile, vechimea companiei, tipul de activitate, structura consorțiului sau lipsa datoriilor.', tags: ['aplicare', 'granturi'] },
  { slug: 'elevator-pitch', term: 'Elevator pitch', body: 'Prezentare foarte scurtă a startupului, de 30–60 de secunde.\n\nStructură simplă: problema, soluția, pentru cine, de ce acum, ce tracțiune există și ce cauți.', tags: ['fundraising', 'aplicare'] },
  { slug: 'equity', term: 'Equity', body: 'Procent din companie oferit investitorilor, acceleratorului, angajaților sau advisorilor.\n\nEquity-ul este o resursă strategică și trebuie gestionat atent, mai ales la startupuri early-stage.', tags: ['investitii', 'fundraising'] },
  { slug: 'evaluator', term: 'Evaluator', body: 'Persoană sau comisie care analizează aplicațiile și decide ce proiecte primesc finanțare.\n\nEvaluatorii caută claritate, eligibilitate, impact, fezabilitate, inovație, echipă bună și riscuri gestionabile.', tags: ['granturi', 'aplicare'] },
  { slug: 'exit', term: 'Exit', body: 'Momentul în care fondatorii sau investitorii își vând participația, de obicei prin achiziție, fuziune sau listare publică.', tags: ['investitii', 'fundraising'] },

  // F
  { slug: 'feasibility-study', term: 'Feasibility study', body: 'Studiu care arată dacă o idee, tehnologie sau proiect este realist, implementabil și justificat economic.\n\nEste des folosit în granturi R&D și proiecte tehnologice.', tags: ['granturi', 'trl-deeptech', 'aplicare'] },
  { slug: 'financial-model', term: 'Financial model', body: 'Model financiar care arată veniturile, costurile, profitabilitatea, cash flow-ul, runway-ul, scenariile de creștere și nevoia de finanțare.\n\nUn model financiar bun permite evaluatorilor să înțeleagă cum vor fi folosiți banii și dacă planul este credibil.', tags: ['aplicare', 'buget', 'fundraising'] },
  { slug: 'finantare-privata', term: 'Finanțare privată', body: 'Bani oferiți de investitori, fonduri VC, angel investors, companii, acceleratoare private, family offices sau parteneri strategici.', tags: ['investitii', 'fundraising'] },
  { slug: 'finantare-publica', term: 'Finanțare publică', body: 'Bani oferiți de instituții publice, guverne, agenții naționale, Uniunea Europeană sau programe internaționale.\n\nFinanțarea publică este adesea non-dilutivă, dar vine cu reguli, raportare și criterii stricte.', tags: ['granturi', 'ue'] },
  { slug: 'fond-investitii', term: 'Fond de investiții', body: 'Organizație care investește capital în companii, de obicei în schimbul equity.\n\nFondurile VC caută startupuri scalabile, piețe mari, echipe puternice și potențial de exit.', tags: ['investitii', 'fundraising'] },
  { slug: 'fondator', term: 'Fondator', body: 'Persoana care a creat startupul și are un rol esențial în dezvoltarea companiei.\n\nÎn aplicații și fundraising, calitatea echipei fondatoare este unul dintre cele mai importante criterii.', tags: ['startup-basics', 'ecosistem'] },
  { slug: 'founder-market-fit', term: 'Founder-market fit', body: 'Potrivirea dintre fondator și piața pe care o atacă.\n\nEvaluatorii caută experiență relevantă, acces la clienți, înțelegere profundă a problemei, motivație și credibilitate.', tags: ['startup-basics', 'fundraising'] },
  { slug: 'freemium', term: 'Freemium', body: 'Model în care produsul are o versiune gratuită și una plătită cu funcții avansate.', tags: ['produs', 'startup-basics'] },
  { slug: 'fundraising', term: 'Fundraising', body: 'Procesul de atragere a capitalului de la investitori, granturi, acceleratoare, competiții sau alte surse.\n\nUn proces bun de fundraising include pregătirea documentelor, pipeline de finanțatori, pitch, negocieri și due diligence.', tags: ['fundraising'] },
  { slug: 'funding-fit', term: 'Funding fit', body: 'Potrivirea dintre startup și o sursă de finanțare.\n\nInclude sector, țară, stadiu, sumă, TRL, tip capital, eligibilitate, deadline și nivel de pregătire.', tags: ['scoring', 'fundraising', 'aplicare'] },
  { slug: 'funding-roadmap', term: 'Funding roadmap', body: 'Plan care arată ce finanțări ar trebui urmărite în următoarele 3–18 luni.\n\nUn roadmap bun nu include doar oportunități imediate, ci și pașii necesari pentru a deveni eligibil la programe mai mari.', tags: ['fundraising', 'aplicare'] },

  // G
  { slug: 'gap-analysis', term: 'Gap analysis', body: 'Analiză care arată diferența dintre starea actuală a startupului și cerințele unui program.', example: 'Startupul are TRL 4, dar programul cere TRL 6. Gap analysis arată ce experimente, validări sau documente lipsesc.', tags: ['scoring', 'aplicare'] },
  { slug: 'gtm', term: 'Go-to-market / GTM', body: 'Strategia prin care startupul intră pe piață și atrage clienți.\n\nInclude segment țintă, canale, pricing, mesaj, sales motion, parteneriate, metrici și timeline.', tags: ['growth', 'produs'] },
  { slug: 'grant', term: 'Grant', body: 'Finanțare nerambursabilă oferită pentru un proiect, fără cedare de equity.\n\nUnele granturi cer cofinanțare, raportare, milestone-uri, justificarea cheltuielilor și livrabile clare.', tags: ['granturi', 'fundraising'] },
  { slug: 'grant-colaborativ', term: 'Grant colaborativ', body: 'Grant unde mai multe organizații aplică împreună într-un consorțiu.', example: 'Horizon Europe Cluster Health.', tags: ['granturi', 'consortii', 'ue'] },
  { slug: 'grant-non-dilutiv', term: 'Grant non-dilutiv', body: 'Grant care nu cere cedarea unui procent din companie.\n\nEste una dintre cele mai atractive forme de finanțare pentru startupuri, mai ales în faze de cercetare sau validare tehnologică.', tags: ['granturi', 'fundraising'] },
  { slug: 'gross-margin', term: 'Gross margin', body: 'Diferența dintre venituri și costurile directe asociate livrării produsului sau serviciului.\n\nGross margin este important pentru a înțelege cât de scalabil este modelul de business.', tags: ['metrici', 'buget'] },
  { slug: 'growth', term: 'Growth', body: 'Etapa în care startupul scalează după ce a validat produsul, piața și modelul de business.', tags: ['growth', 'startup-basics'] },
  { slug: 'growth-hacking', term: 'Growth hacking', body: 'Testare rapidă de tactici de creștere pentru a găsi canale eficiente de acquisition, activation, retention sau referral.', tags: ['growth'] },

  // H
  { slug: 'hardware-startup', term: 'Hardware startup', body: 'Startup care dezvoltă produse fizice, dispozitive, senzori, echipamente sau sisteme integrate hardware-software.\n\nHardware startups au de obicei costuri mai mari, cicluri mai lungi și nevoi de prototipare, certificare și producție.', tags: ['trl-deeptech', 'produs'] },
  { slug: 'horizon-europe', term: 'Horizon Europe', body: 'Programul principal al Uniunii Europene pentru cercetare și inovare.\n\nInclude granturi mari pentru cercetare, startupuri, IMM-uri, universități, institute și consorții. Este relevant pentru deep tech, health, climate, digital, space, industrie și impact social.', tags: ['ue', 'granturi', 'consortii'] },

  // I
  { slug: 'icp', term: 'ICP / Ideal Customer Profile', body: 'Profilul clientului ideal.\n\nInclude industrie, dimensiune, buget, problemă, rol decizional, regiune, comportament și criterii de cumpărare.', tags: ['produs', 'growth'] },
  { slug: 'impact', term: 'Impact', body: 'Efectul așteptat al proiectului asupra pieței, societății, mediului, economiei sau domeniului științific.\n\nÎn aplicații, impactul trebuie să fie clar, măsurabil, credibil și conectat la obiectivele programului.', tags: ['granturi', 'aplicare'] },
  { slug: 'impact-report', term: 'Impact report', body: 'Document care explică rezultatele și efectele unui proiect, inclusiv indicatori, rezultate, beneficiari și schimbări produse.', tags: ['granturi', 'aplicare'] },
  { slug: 'imm', term: 'IMM', body: 'Întreprindere mică sau mijlocie.\n\nMulte granturi europene sunt dedicate IMM-urilor inovatoare, deoarece acestea pot transforma rapid cercetarea și tehnologia în produse comerciale.', tags: ['ue', 'granturi', 'ecosistem'] },
  { slug: 'incubator', term: 'Incubator', body: 'Program care ajută ideile sau startupurile foarte timpurii să se formeze prin mentorat, training, spațiu, comunitate și suport operațional.', tags: ['acceleratoare', 'ecosistem'] },
  { slug: 'innovation', term: 'Innovation', body: 'Elementul nou al produsului, tehnologiei, procesului sau modelului de business.\n\nEvaluatorii caută de ce soluția este diferită, greu de copiat, relevantă pentru piață și superioară alternativelor existente.', tags: ['startup-basics', 'aplicare'] },
  { slug: 'ip', term: 'Intellectual Property / IP', body: 'Proprietate intelectuală.\n\nInclude brevete, cod sursă, know-how, mărci, design, baze de date, algoritmi, documentație tehnică sau secrete comerciale.', tags: ['trl-deeptech', 'aplicare'] },
  { slug: 'investor-update', term: 'Investor update', body: 'Email periodic trimis investitorilor sau potențialilor investitori cu progresul startupului.\n\nInclude metrici, realizări, probleme, nevoi, ask-uri și planuri.', tags: ['fundraising', 'investitii'] },

  // K
  { slug: 'key-metric', term: 'Key metric', body: 'Indicator principal care arată sănătatea startupului.', example: 'MRR, ARR, churn, retention, CAC, LTV, active users, gross margin.', tags: ['metrici'] },
  { slug: 'kpi', term: 'KPI', body: 'Indicator cheie de performanță.\n\nAjută la măsurarea progresului unui startup sau proiect finanțat.', example: 'Număr de utilizatori, venit lunar, cost de achiziție client, reducere de emisii, prototip validat, număr de parteneri.', tags: ['metrici', 'aplicare'] },

  // L
  { slug: 'landing-page', term: 'Landing page', body: 'Pagină web construită pentru o acțiune clară: înscriere, demo request, waitlist, download, aplicare sau achiziție.', tags: ['produs', 'growth'] },
  { slug: 'lean-startup', term: 'Lean startup', body: 'Metodologie de construire a startupurilor prin testare rapidă, feedback de la clienți și iterare continuă.\n\nPrincipiul central este să validezi ipotezele înainte să investești prea mult timp sau bani.', tags: ['startup-basics', 'produs'] },
  { slug: 'loi', term: 'Letter of Intent / LOI', body: 'Scrisoare prin care un potențial client, partener sau investitor își exprimă interesul pentru produs, colaborare sau proiect.\n\nLOI-urile pot crește credibilitatea unei aplicații de grant sau investiție.', tags: ['aplicare', 'fundraising'] },
  { slug: 'letter-of-support', term: 'Letter of Support', body: 'Scrisoare de susținere din partea unui partener, client, instituție, mentor sau expert.\n\nPoate ajuta aplicația să pară mai credibilă, mai validată și mai conectată la piață.', tags: ['aplicare', 'granturi'] },
  { slug: 'ltv', term: 'LTV / Lifetime Value', body: 'Valoarea totală estimată pe care un client o aduce pe durata relației cu startupul.\n\nLTV este analizat împreună cu CAC. Dacă LTV este mult mai mare decât CAC, modelul poate fi scalabil.', tags: ['metrici', 'growth'] },

  // M
  { slug: 'market-size', term: 'Market size', body: 'Dimensiunea pieței pe care o poate ataca startupul.\n\nTermenii asociați sunt TAM, SAM și SOM.', tags: ['startup-basics', 'metrici'] },
  { slug: 'marketplace', term: 'Marketplace', body: 'Model de business care conectează două sau mai multe grupuri de utilizatori.', example: 'Vânzători și cumpărători, freelanceri și clienți, startupuri și finanțatori.', tags: ['startup-basics', 'produs'] },
  { slug: 'match-score', term: 'Match Score', body: 'Scor care arată cât de bine se potrivește startupul cu un anumit program de finanțare.\n\nPoate lua în calcul țara, domeniul, TRL-ul, stadiul, suma dorită, tipul de capital, deadline-ul, documentele existente și cerințele programului.', tags: ['scoring'] },
  { slug: 'milestone', term: 'Milestone', body: 'Rezultat important care trebuie atins într-un proiect.', example: 'Prototip funcțional, test pilot, primii 100 de clienți, certificare, lansare MVP, obținerea unei aprobări tehnice.', tags: ['aplicare', 'granturi'] },
  { slug: 'moat', term: 'Moat', body: 'Avantaj defensibil care protejează startupul de competitori.', example: 'IP, date exclusive, efecte de rețea, costuri de schimbare ridicate, brand, distribuție unică.', tags: ['startup-basics', 'produs'] },
  { slug: 'mrr', term: 'MRR / Monthly Recurring Revenue', body: 'Venit lunar recurent, folosit mai ales pentru SaaS și abonamente.\n\nMRR ajută la înțelegerea creșterii și predictibilității veniturilor.', tags: ['metrici'] },
  { slug: 'mvp', term: 'MVP / Minimum Viable Product', body: 'Cea mai simplă versiune funcțională a produsului, suficientă pentru testare cu utilizatori reali.\n\nUn MVP nu trebuie să fie perfect, ci suficient pentru a valida o ipoteză importantă.', tags: ['startup-basics', 'produs'] },

  // N
  { slug: 'network-effects', term: 'Network effects', body: 'Situație în care produsul devine mai valoros pe măsură ce mai mulți oameni îl folosesc.', example: 'Un marketplace devine mai valoros când are mai mulți vânzători și cumpărători.', tags: ['produs', 'growth'] },
  { slug: 'non-dilutiv', term: 'Non-dilutiv', body: 'Finanțare care nu reduce procentul deținut de fondatori în companie.', example: 'Granturi, premii, vouchere, credite cloud, suport tehnic, mentorat fără equity.', tags: ['granturi', 'fundraising'] },
  { slug: 'north-star-metric', term: 'North Star Metric', body: 'Metrică principală care reflectă valoarea livrată utilizatorilor și creșterea companiei.\n\nO North Star Metric bună conectează produsul, retenția și impactul businessului.', tags: ['metrici', 'produs'] },

  // O
  { slug: 'one-pager', term: 'One-pager', body: 'Document de o pagină care prezintă startupul pe scurt.\n\nInclude problemă, soluție, piață, produs, echipă, tracțiune, nevoi și contact.', tags: ['aplicare', 'fundraising'] },
  { slug: 'onboarding', term: 'Onboarding', body: 'Procesul prin care un utilizator nou este ghidat să înțeleagă și să folosească produsul.\n\nÎn eligibil.org, onboarding-ul poate include crearea profilului startupului, încărcarea documentelor și generarea primului raport de eligibilitate.', tags: ['produs', 'startup-basics'] },
  { slug: 'outbound-sales', term: 'Outbound sales', body: 'Proces de vânzare în care startupul contactează activ potențiali clienți prin email, LinkedIn, telefon sau evenimente.', tags: ['growth'] },

  // P
  { slug: 'pathfinder', term: 'Pathfinder', body: 'Program pentru tehnologii emergente, cercetare avansată și idei high-risk / high-gain.\n\nDe obicei necesită consorțiu și este orientat spre faze timpurii de cercetare.', tags: ['ue', 'consortii', 'trl-deeptech'] },
  { slug: 'payback-period', term: 'Payback period', body: 'Perioada necesară pentru a recupera costul de achiziție al unui client.', example: 'Dacă un client costă €300 să fie achiziționat și generează €100 marjă lunară, payback period este de 3 luni.', tags: ['metrici', 'buget'] },
  { slug: 'persona', term: 'Persona', body: 'Profil semi-fictiv al unui tip de utilizator sau client.\n\nInclude rol, nevoi, frici, comportamente, obiective și criterii de decizie.', tags: ['produs', 'growth'] },
  { slug: 'phase-i', term: 'Phase I', body: 'Prima etapă într-un program de tip SBIR/STTR.\n\nDe obicei finanțează validarea tehnică, fezabilitatea și primele experimente.', tags: ['sbir', 'granturi'] },
  { slug: 'phase-ii', term: 'Phase II', body: 'Etapă ulterioară care finanțează dezvoltarea tehnologiei, prototiparea avansată și pregătirea pentru comercializare.', tags: ['sbir', 'granturi'] },
  { slug: 'phase-iii', term: 'Phase III', body: 'Etapă de comercializare, de obicei fără grant direct SBIR, dar cu acces la contracte, clienți, achiziții publice sau finanțare privată.', tags: ['sbir', 'granturi'] },
  { slug: 'pilot', term: 'Pilot', body: 'Test al produsului cu un client sau partener, de obicei înainte de contract comercial complet.\n\nUn pilot poate fi plătit sau gratuit și poate deveni dovadă de tracțiune.', tags: ['produs', 'startup-basics'] },
  { slug: 'pitch-deck', term: 'Pitch deck', body: 'Prezentare scurtă a startupului, folosită pentru investitori, granturi, acceleratoare sau parteneri.\n\nInclude de obicei problemă, soluție, piață, produs, business model, tracțiune, competiție, echipă, plan financiar și ask.', tags: ['aplicare', 'fundraising'] },
  { slug: 'pitch-video', term: 'Pitch video', body: 'Video scurt în care fondatorul prezintă startupul.\n\nEste folosit frecvent de acceleratoare, competiții și unele granturi pentru a evalua claritatea, energia, storytellingul și capacitatea de comunicare.', tags: ['aplicare', 'acceleratoare'] },
  { slug: 'pivot', term: 'Pivot', body: 'Schimbare importantă de strategie, piață, produs sau model de business după validări sau feedback.', tags: ['startup-basics', 'produs'] },
  { slug: 'pmf', term: 'PMF / Product-Market Fit', body: 'Momentul în care produsul rezolvă o problemă reală pentru o piață suficient de mare, iar clienții îl folosesc, plătesc și îl recomandă.\n\nPMF este una dintre cele mai importante etape în viața unui startup.', tags: ['startup-basics', 'produs'] },
  { slug: 'pre-seed', term: 'Pre-seed', body: 'Stadiu foarte timpuriu al startupului, de obicei înainte de venituri semnificative sau înainte de produs matur.', tags: ['fundraising', 'investitii'] },
  { slug: 'pricing', term: 'Pricing', body: 'Strategia de preț.', example: 'Abonament, freemium, usage-based, per user, per seat, enterprise license, comision.', tags: ['produs', 'growth'] },
  { slug: 'prime-contractor', term: 'Prime contractor', body: 'Organizația principală care semnează contractul cu finanțatorul și poate lucra cu subcontractori sau parteneri.\n\nRelevant pentru unele programe americane, inclusiv colaborări prin entități SUA.', tags: ['sbir', 'consortii'] },
  { slug: 'product-roadmap', term: 'Product roadmap', body: 'Plan care arată ce funcționalități sau îmbunătățiri vor fi dezvoltate în timp.\n\nÎn granturi, roadmap-ul poate fi conectat la milestone-uri și work packages.', tags: ['produs', 'aplicare'] },
  { slug: 'poc', term: 'Proof of Concept / PoC', body: 'Demonstrație că ideea sau tehnologia poate funcționa în principiu.\n\nUn PoC este mai puțin matur decât un MVP, dar foarte important în deep tech și R&D.', tags: ['trl-deeptech', 'produs'] },
  { slug: 'proprietate-intelectuala', term: 'Proprietate intelectuală', body: 'Active intangibile create de startup.', example: 'Brevete, software, algoritmi, design, know-how, mărci, documentație tehnică.', tags: ['trl-deeptech', 'aplicare'] },
  { slug: 'prototype', term: 'Prototype', body: 'Versiune demonstrativă a produsului, folosită pentru testare, validare sau prezentare.', tags: ['produs', 'trl-deeptech'] },

  // R
  { slug: 'rd', term: 'R&D / Research and Development', body: 'Activități de cercetare și dezvoltare pentru crearea sau îmbunătățirea unei tehnologii.\n\nR&D este important în granturi, deep tech, hardware, biotech, AI și proiecte cu risc tehnologic.', tags: ['trl-deeptech', 'granturi'] },
  { slug: 'readiness-score', term: 'Readiness Score', body: 'Scor care arată cât de pregătit este startupul pentru a aplica la un program.\n\nPoate include documente existente, claritatea pitchului, buget, TRL, echipă, tracțiune, parteneri, dovezi de piață și nivelul de completitudine al aplicației.', tags: ['scoring'] },
  { slug: 'reimbursable-grant', term: 'Reimbursable grant', body: 'Grant în care cheltuielile sunt rambursate după ce au fost realizate și justificate.\n\nStartupul trebuie să aibă cash flow suficient pentru a suporta cheltuielile până la rambursare.', tags: ['granturi', 'buget'] },
  { slug: 'research-grant', term: 'Research grant', body: 'Grant destinat cercetării, experimentelor, prototipării sau validării științifice.\n\nEste potrivit pentru tehnologii aflate înainte de comercializare.', tags: ['granturi', 'trl-deeptech'] },
  { slug: 'researchmatch', term: 'ResearchMatch', body: 'Proces de potrivire între startup, cercetători, institute, universități sau consorții relevante pentru granturi R&D.', tags: ['consortii', 'trl-deeptech'] },
  { slug: 'retention', term: 'Retention', body: 'Capacitatea startupului de a păstra utilizatorii sau clienții în timp.\n\nRetention bun indică valoare reală, produs util și potrivire mai bună cu piața.', tags: ['metrici', 'produs'] },
  { slug: 'revenue-model', term: 'Revenue model', body: 'Modul concret prin care startupul generează venituri.', example: 'Abonamente, licențe, comisioane, tranzacții, servicii, advertising, usage-based billing.', tags: ['startup-basics', 'produs'] },
  { slug: 'roadmap', term: 'Roadmap', body: 'Plan de dezvoltare pentru produs, business, tehnologie sau finanțare.', tags: ['produs', 'fundraising'] },
  { slug: 'rolling-application', term: 'Rolling application', body: 'Program care acceptă aplicații continuu, fără un singur deadline fix.', tags: ['granturi', 'aplicare'] },
  { slug: 'runway', term: 'Runway', body: 'Numărul de luni în care startupul poate funcționa cu banii disponibili.\n\nRunway-ul este calculat pe baza cash-ului disponibil și burn rate-ului lunar.', tags: ['metrici', 'buget'] },

  // S
  { slug: 'saas', term: 'SaaS / Software as a Service', body: 'Model de business în care produsul software este oferit ca abonament.\n\nSaaS este atractiv pentru investitori datorită veniturilor recurente și scalabilității.', tags: ['startup-basics', 'produs'] },
  { slug: 'sales-funnel', term: 'Sales funnel', body: 'Procesul prin care un potențial client ajunge de la primul contact la achiziție.', example: 'Lead, qualified lead, demo, proposal, negotiation, closed won.', tags: ['growth'] },
  { slug: 'sam', term: 'SAM / Serviceable Available Market', body: 'Partea din TAM pe care startupul o poate servi realist cu produsul și modelul actual.', tags: ['metrici', 'startup-basics'] },
  { slug: 'scaleup', term: 'Scaleup', body: 'Companie care a trecut de etapa startup și crește accelerat, cu venituri, echipă și procese mai mature.', tags: ['growth', 'ecosistem'] },
  { slug: 'sbir', term: 'SBIR', body: 'Small Business Innovation Research.\n\nProgram american de granturi pentru startupuri și companii mici care dezvoltă tehnologii inovatoare. Este relevant pentru R&D, deep tech, hardware, biotech și tehnologii avansate.', tags: ['sbir', 'granturi', 'trl-deeptech'] },
  { slug: 'seed', term: 'Seed', body: 'Stadiu de finanțare după pre-seed, când startupul are de obicei MVP, validare inițială, clienți sau tracțiune.', tags: ['fundraising', 'investitii'] },
  { slug: 'seed-round', term: 'Seed round', body: 'Rundă de finanțare pentru startupuri aflate la început, de obicei după MVP și validare inițială.', tags: ['fundraising', 'investitii'] },
  { slug: 'sme', term: 'SME', body: 'Small and Medium-sized Enterprise. Echivalentul IMM în limba engleză.', tags: ['ue', 'ecosistem'] },
  { slug: 'som', term: 'SOM / Serviceable Obtainable Market', body: 'Partea din SAM pe care startupul o poate câștiga realist într-o perioadă definită.', tags: ['metrici', 'startup-basics'] },
  { slug: 'soft-launch', term: 'Soft launch', body: 'Lansare limitată a produsului către un grup mic de utilizatori înainte de lansarea oficială.', tags: ['produs'] },
  { slug: 'spinout', term: 'Spinout', body: 'Companie creată pe baza unei tehnologii, cercetări sau IP provenite dintr-o universitate, institut sau organizație existentă.\n\nSpinout-urile sunt relevante pentru granturi R&D, EIC, Horizon Europe și programe deep tech.', tags: ['trl-deeptech', 'ue', 'granturi'] },
  { slug: 'startup', term: 'Startup', body: 'Companie tânără, inovatoare, cu potențial de creștere rapidă și model scalabil.\n\nUn startup nu este doar o companie mică. Diferența este ambiția de scalare, incertitudinea ridicată și nevoia de validare rapidă.', tags: ['startup-basics'] },
  { slug: 'startup-ecosystem', term: 'Startup ecosystem', body: 'Rețeaua de actori care susțin startupurile.\n\nInclude fondatori, investitori, acceleratoare, universități, granturi, mentori, comunități, hub-uri, companii și instituții publice.', tags: ['ecosistem'] },
  { slug: 'startup-profile', term: 'Startup profile', body: 'Profil standardizat al startupului în eligibil.org.\n\nInclude domeniu, țară, stadiu, echipă, produs, TRL, tracțiune, documente, nevoi de finanțare și tip capital preferat.', tags: ['scoring', 'aplicare'] },
  { slug: 'sttr', term: 'STTR', body: 'Small Business Technology Transfer.\n\nProgram american similar SBIR, dar cu accent mai mare pe colaborarea între companie și instituții de cercetare.', tags: ['sbir', 'consortii', 'granturi'] },
  { slug: 'subcontractare', term: 'Subcontractare', body: 'Activitate externalizată către o altă companie sau expert pentru a realiza o parte din proiect.\n\nÎn granturi, subcontractarea trebuie justificată și uneori aprobată explicit.', tags: ['buget', 'granturi'] },
  { slug: 'suggested-actions', term: 'Suggested actions', body: 'Acțiuni recomandate după analiză.', example: 'Rescrie pitch deck, pregătește buget, caută partener, crește TRL, adaugă LOI, aplică la accelerator.', tags: ['scoring', 'aplicare'] },

  // T
  { slug: 'tam', term: 'TAM / Total Addressable Market', body: 'Piața totală pe care startupul ar putea-o ataca teoretic.\n\nTAM arată dimensiunea maximă a oportunității.', tags: ['metrici', 'startup-basics'] },
  { slug: 'tech-stack', term: 'Tech stack', body: 'Setul de tehnologii folosite pentru construirea produsului.', example: 'Frontend, backend, baze de date, cloud, AI models, analytics, payment systems.', tags: ['produs', 'trl-deeptech'] },
  { slug: 'trl', term: 'Technology Readiness Level / TRL', body: 'Scară de la 1 la 9 care măsoară maturitatea unei tehnologii.\n\nTRL este foarte important în granturi deep tech, EIC, Horizon Europe, SBIR și proiecte R&D.\n\nTRL 1 — Principii de bază observate.\nTRL 2 — Concept tehnologic formulat.\nTRL 3 — Dovadă experimentală de concept.\nTRL 4 — Validare în laborator.\nTRL 5 — Validare într-un mediu relevant.\nTRL 6 — Demonstrație în mediu relevant.\nTRL 7 — Prototip demonstrat în mediu operațional.\nTRL 8 — Sistem complet și calificat.\nTRL 9 — Sistem testat și utilizat în condiții reale.', tags: ['trl-deeptech', 'granturi', 'ue', 'sbir'] },
  { slug: 'term-sheet', term: 'Term sheet', body: 'Document care descrie termenii principali ai unei investiții: sumă, evaluare, equity, drepturi ale investitorilor, condiții, opțiuni și mecanisme de protecție.', tags: ['investitii', 'fundraising'] },
  { slug: 'traction', term: 'Traction', body: 'Dovezi că startupul are validare în piață.', example: 'Utilizatori, venituri, clienți plătitori, parteneriate, LOI-uri, creștere lunară, piloți activi, retenție bună.', tags: ['metrici', 'aplicare', 'fundraising'] },

  // U
  { slug: 'unit-economics', term: 'Unit economics', body: 'Analiza economică la nivel de client, utilizator sau tranzacție.\n\nInclude CAC, LTV, gross margin, payback period și profitabilitatea per client.', tags: ['metrici', 'buget'] },
  { slug: 'upsell', term: 'Upsell', body: 'Vânzarea unui plan mai scump sau a unor funcții suplimentare către un client existent.', tags: ['growth'] },
  { slug: 'usage-based-pricing', term: 'Usage-based pricing', body: 'Model de preț în care clientul plătește în funcție de utilizare.', example: 'Per API call, per GB, per tranzacție, per analiză, per document procesat.', tags: ['produs', 'startup-basics'] },

  // V
  { slug: 'validation', term: 'Validation', body: 'Procesul prin care verifici că problema, soluția, piața sau modelul de business sunt reale.', example: 'Interviuri cu clienți, pilot, LOI, vânzări, waitlist, test de preț.', tags: ['startup-basics', 'produs'] },
  { slug: 'value-proposition', term: 'Value proposition', body: 'Promisiunea principală de valoare a startupului.\n\nRăspunde la întrebarea: de ce ar alege clientul produsul tău?', tags: ['startup-basics', 'produs'] },
  { slug: 'vc', term: 'VC / Venture Capital', body: 'Fond de investiții care finanțează startupuri cu potențial mare de creștere, de obicei în schimbul equity.\n\nVC-urile caută piețe mari, echipe puternice, creștere rapidă și potențial de exit.', tags: ['investitii', 'fundraising'] },
  { slug: 'venture-backed-startup', term: 'Venture-backed startup', body: 'Startup finanțat de investitori de tip venture capital.', tags: ['investitii', 'startup-basics'] },
  { slug: 'voucher', term: 'Voucher', body: 'Formă de finanțare sau suport care poate fi folosită pentru servicii specifice.', example: 'Voucher pentru digitalizare, consultanță, cloud, IP, cercetare sau prototipare.', tags: ['granturi', 'fundraising'] },

  // W
  { slug: 'waitlist', term: 'Waitlist', body: 'Listă de persoane sau companii interesate să testeze produsul înainte sau imediat după lansare.\n\nO waitlist poate fi dovadă de interes de piață.', tags: ['produs', 'growth'] },
  { slug: 'whitepaper', term: 'Whitepaper', body: 'Document tehnic care explică tehnologia, metodologia, problema, soluția, arhitectura, validarea, TRL-ul, IP-ul și impactul.\n\nEste folosit în deep tech, blockchain, AI, biotech, cercetare, EIC, Horizon Europe sau granturi R&D.', tags: ['trl-deeptech', 'aplicare', 'granturi'] },
  { slug: 'work-package', term: 'Work Package / WP', body: 'Bloc de activități într-un proiect finanțat, cu obiective, livrabile, buget, timeline și responsabilități.', example: 'WP1 — Management, WP2 — Cercetare, WP3 — Prototipare, WP4 — Validare, WP5 — Dissemination.', tags: ['granturi', 'consortii', 'aplicare'] },
];

window.ORG_GLOSAR = ORG_GLOSAR;

// Categorii pentru filtre — derivate din lista de tag-uri
window.GLOSAR_TAGS = [
  { id: 'startup-basics',   label: 'Startup basics' },
  { id: 'granturi',         label: 'Granturi' },
  { id: 'investitii',       label: 'Investiții' },
  { id: 'acceleratoare',    label: 'Acceleratoare' },
  { id: 'ue',               label: 'Uniunea Europeană' },
  { id: 'sbir',             label: 'SBIR / SUA' },
  { id: 'trl-deeptech',     label: 'TRL & deep tech' },
  { id: 'consortii',        label: 'Consorții' },
  { id: 'aplicare',         label: 'Documente de aplicare' },
  { id: 'scoring',          label: 'Scoring AI' },
  { id: 'buget',            label: 'Buget & raportare' },
  { id: 'produs',           label: 'Produs' },
  { id: 'metrici',          label: 'Metrici' },
  { id: 'growth',           label: 'Growth' },
  { id: 'fundraising',      label: 'Fundraising' },
  { id: 'ecosistem',        label: 'Ecosistem' },
];

window.GLOSAR_POPULAR = [
  'TRL', 'capital non-dilutiv', 'EIC Accelerator', 'SBIR', 'consorțiu',
  'Match Score', 'Readiness Score', 'MVP', 'PMF', 'CAC', 'LTV', 'burn rate',
  'runway', 'cap table', 'go-to-market', 'founder-market fit', 'cofinanțare',
  'buget eligibil', 'pitch deck',
];
