# =============================================================================
# eligibil.org — idempotent Koyeb Free deployment
#
# Usage:
#   .\scripts\deploy-koyeb.ps1
#   .\scripts\deploy-koyeb.ps1 -EnvFile C:\secure\eligibil.env
#
# The script never prints secret values and sends them to Koyeb through stdin.
# =============================================================================

param(
    [string]$EnvFile = (Join-Path (Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)) '.env'),
    [string]$AppName = 'eligibil',
    [string]$ServiceName = 'web',
    [string]$Repository = 'github.com/duediligenceonemd/eligibil',
    [string]$Branch = 'master',
    [string]$Region = 'fra'
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $RepoRoot

function Read-DotEnv {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Environment file not found: $Path"
    }

    $result = @{}
    foreach ($rawLine in Get-Content -LiteralPath $Path) {
        $line = $rawLine.Trim()
        if (-not $line -or $line.StartsWith('#') -or -not $line.Contains('=')) { continue }

        $parts = $line -split '=', 2
        $key = $parts[0].Trim()
        $value = $parts[1].Trim()
        if (($value.StartsWith('"') -and $value.EndsWith('"')) -or
            ($value.StartsWith("'") -and $value.EndsWith("'"))) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        if ($key -match '^[A-Z][A-Z0-9_]*$') { $result[$key] = $value }
    }
    return $result
}

function New-RandomSecret {
    $bytes = New-Object byte[] 48
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Invoke-Koyeb {
    param([Parameter(ValueFromRemainingArguments = $true)][string[]]$Arguments)
    & koyeb @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Koyeb command failed: koyeb $($Arguments -join ' ')"
    }
}

function Test-KoyebResource {
    param([Parameter(Mandatory = $true)][string[]]$Arguments)
    & koyeb @Arguments *> $null
    return $LASTEXITCODE -eq 0
}

function Set-KoyebSecret {
    param(
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][string]$Value
    )

    $verb = if (Test-KoyebResource @('secrets', 'get', $Name)) { 'update' } else { 'create' }
    $startInfo = [System.Diagnostics.ProcessStartInfo]::new()
    $startInfo.FileName = (Get-Command koyeb).Source
    $startInfo.UseShellExecute = $false
    $startInfo.RedirectStandardInput = $true
    $startInfo.RedirectStandardOutput = $true
    $startInfo.RedirectStandardError = $true
    # These values are generated by this script and contain only safe slug
    # characters. Secret material is written to stdin, never to Arguments.
    $startInfo.Arguments = "secrets $verb $Name --value-from-stdin"

    $process = [System.Diagnostics.Process]::new()
    $process.StartInfo = $startInfo
    [void]$process.Start()
    $process.StandardInput.Write($Value)
    $process.StandardInput.Close()
    $stdout = $process.StandardOutput.ReadToEnd()
    $stderr = $process.StandardError.ReadToEnd()
    $process.WaitForExit()
    if ($process.ExitCode -ne 0) {
        throw "Unable to $verb Koyeb secret '$Name': $stderr"
    }
    Write-Host "  $Name ($verb)"
}

if (-not (Get-Command koyeb -ErrorAction SilentlyContinue)) {
    throw 'Koyeb CLI not found. Install it from https://github.com/koyeb/koyeb-cli/releases/latest'
}

Invoke-Koyeb whoami
$envValues = Read-DotEnv -Path $EnvFile

foreach ($required in @('SUPABASE_URL', 'SUPABASE_SERVICE_KEY', 'SESSION_SECRET')) {
    if (-not $envValues.ContainsKey($required) -or [string]::IsNullOrWhiteSpace($envValues[$required])) {
        throw "Missing required production value: $required"
    }
}

$secretKeys = @(
    'SUPABASE_URL',
    'SUPABASE_SERVICE_KEY',
    'SESSION_SECRET',
    'UNSUBSCRIBE_SECRET',
    'AWS_ACCESS_KEY_ID',
    'AWS_SECRET_ACCESS_KEY',
    'OPENAI_API_KEY',
    'ANTHROPIC_API_KEY',
    'SENTRY_DSN',
    'RESEND_API_KEY',
    'ADMIN_TOKEN',
    'GMAIL_USER',
    'GMAIL_APP_PASSWORD'
)

$secretReferences = @{}
Write-Host 'Synchronizing production secrets:'
foreach ($key in $secretKeys) {
    $secretName = 'eligibil-' + $key.ToLowerInvariant().Replace('_', '-')
    $hasLocalValue = $envValues.ContainsKey($key) -and -not [string]::IsNullOrWhiteSpace($envValues[$key])
    $secretExists = Test-KoyebResource @('secrets', 'get', $secretName)

    if ($key -eq 'UNSUBSCRIBE_SECRET' -and -not $hasLocalValue) {
        if (-not $secretExists) {
            Set-KoyebSecret -Name $secretName -Value (New-RandomSecret)
        } else {
            Write-Host "  $secretName (unchanged)"
        }
        $secretReferences[$key] = "{{secret.$secretName}}"
        continue
    }

    if (-not $hasLocalValue) { continue }
    Set-KoyebSecret -Name $secretName -Value $envValues[$key]
    $secretReferences[$key] = "{{secret.$secretName}}"
}

$plainEnvironment = [ordered]@{
    NODE_ENV = 'production'
    PORT = '8080'
    SESSION_STORE = 'supabase'
    SESSION_TABLE = 'app_sessions'
    SESSION_MAX_AGE_MS = '86400000'
    SITE_URL = 'https://eligibil.org'
    BASE_URL = 'https://eligibil.org'
    ALLOW_ADMIN_TOKEN_AUTH = 'false'
}

foreach ($key in @(
    'AWS_REGION',
    'AWS_BEDROCK_EMBEDDINGS',
    'AWS_CHAT_MODEL',
    'AWS_HAIKU_MODEL',
    'AWS_EMBED_MODEL',
    'GA_MEASUREMENT_ID',
    'SENTRY_ENABLE_LOGS',
    'SENTRY_TRACES_SAMPLE_RATE',
    'SENTRY_PROFILE_SESSION_SAMPLE_RATE',
    'SENTRY_PROFILE_LIFECYCLE',
    'SENTRY_SEND_DEFAULT_PII',
    'EMAIL_FROM',
    'EMAIL_REPLY_TO',
    'ADMIN_EMAILS',
    'PASSWORD_RESET_TTL_MINUTES'
)) {
    if ($envValues.ContainsKey($key) -and -not [string]::IsNullOrWhiteSpace($envValues[$key])) {
        $plainEnvironment[$key] = $envValues[$key]
    }
}

$environmentArguments = @()
foreach ($entry in $plainEnvironment.GetEnumerator()) {
    $environmentArguments += @('--env', "$($entry.Key)=$($entry.Value)")
}
foreach ($entry in $secretReferences.GetEnumerator()) {
    $environmentArguments += @('--env', "$($entry.Key)=$($entry.Value)")
}

if (-not (Test-KoyebResource @('apps', 'get', $AppName))) {
    Invoke-Koyeb apps create $AppName
}

$serviceExists = Test-KoyebResource @('services', 'get', $ServiceName, '--app', $AppName)
$serviceArguments = @(
    '--git', $Repository,
    '--git-branch', $Branch,
    '--git-builder', 'docker',
    '--git-docker-dockerfile', 'Dockerfile',
    '--instance-type', 'free',
    '--regions', $Region,
    '--ports', '8080:http',
    '--routes', '/:8080',
    '--checks', '8080:http:/',
    '--checks-grace-period', '8080=30'
) + $environmentArguments + @('--wait', '--wait-timeout', '10m')

if ($serviceExists) {
    Write-Host "Updating Koyeb service $AppName/$ServiceName..."
    Invoke-Koyeb services update "$AppName/$ServiceName" @serviceArguments
} else {
    Write-Host "Creating Koyeb service $AppName/$ServiceName..."
    Invoke-Koyeb services create $ServiceName --app $AppName @serviceArguments
}

Write-Host 'Koyeb deployment is healthy.'
Invoke-Koyeb services get $ServiceName --app $AppName
